language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

env:
   - DB=sqlite3
#  - DB=mysql
#  - DB=pgsql

before_script: composer install --dev --prefer-source

notifications:
  email: hello@rootlogin.ch