site_name: UserProvider
site_description: An user and login provider for the Silex framework.
site_author: Simon Erhardt

repo_name: "Silex UserProvider on GitHub"
repo_url: https://github.com/chrootlogin/silex-userprovider

theme: readthedocs
pages:
  - 'Home': 'index.md'
  - 'Usage': 'usage.md'
  - 'Configuration': 'configuration.md'
  - 'Developer documentation': 'developer_documentation.md'
  - 'Project documentation': 'project_documentation.md'
  - 'Changelog': 'changelog.md'